### ISSUE TITLE
Fail on error when baking

### ISSUE THREAD

**Issue by kwin** [jbake-org/jbake-maven-plugin#13]
Currently, in case baking fails with an error the build is still successful. Instead, it should be configurable if the build should break in case of baking errors (compare with this commit from another JBake Maven Plugin: https://github.com/bildschirmarbeiter/jbake-maven-plugin/commit/0f3d8c8e3647e14cf28c8020d17bfd224a7788d2)

**Comment by jonbullock** [comment]
Thanks for raising this.
