### ISSUE TITLE
Example? no template engine found for *.ftl

### ISSUE THREAD

**Issue by raDiesle** [jbake-org/jbake-maven-plugin#20]
How to use it ?

It tells that no template engine found for *.ftl

guess it is a duplicate of https://github.com/jbake-org/jbake-maven-plugin/issues/14

**Comment by rhwood** [comment]
See https://github.com/jonbullock/maven-jbake-site/blob/master/pom.xml for an example.

**Comment by jonbullock** [comment]
As implied in the link @rhwood provided, the template engines are declared as optional on jbake-core so you have to explicitly declare the template engine you are using as a dependency.

I've created #25 to improve the documentation so this is more clear.
