### ISSUE TITLE
img.path.prepend.host=false does not work

### ISSUE THREAD

**Issue by ascheman** [jbake-org/jbake-maven-plugin#21]
For some reason `img.path.prepend.host=false` did not work with the current `0.3.1` release of this plugin. Probably this was an error in the aggregated JBake 2.6.1?

Incorporating the PR #18 of @hd42 (update to JBake 2.6.3) solved the issue.

**Comment by gorzala** [comment]
Hey, I am also having this problem. @ascheman already filed a PR some time ago. Is someone willing to review (we proper rights)?
