### ISSUE TITLE
Test compatibility with ingenieux/jbake-maven-plugin/ to prepare a release

### ISSUE THREAD

**Issue by kinow** [jbake-org/jbake-maven-plugin#4]
Hi, following up on a comment in https://github.com/ingenieux/jbake-maven-plugin/issues/18, I'm testing the current SNAPSHOT version in this git repository.

I cloned the repository, then changed the version to `0.99-SNAPSHOT`. Then ran `mvn clean install`.

Finally, updated [Apache OpenNLP site](https://github.com/apache/opennlp-site) in my local cloned repo, to use this plug-in. It successfully built the site, and I could see the local copy of the web site, just like in https://opennlp.apache.org, even confirmed asciidoctors tags with variable substitutions. All looking good. 

What else would we need to test to prepare a release to Maven Central?

My environment:

```
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-11T05:41:47+13:00)
Maven home: /opt/maven
Java version: 1.8.0_131, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.4.0-78-generic", arch: "amd64", family: "unix"
```

**Comment by jonbullock** [comment]
Thanks @kinow I need to update the coords and then we should be ready to push a release to Maven Central.

**Comment by jonbullock** [comment]
Version 0.2.0 has been released to Maven Central, could you test the release if you get chance?

**Comment by kinow** [comment]
Sure thing. Will try this new version with OpenNLP site tonight. Thanks @jonbullock !!!

**Comment by kinow** [comment]
Worked like a charm @jonbullock ! Submitted a pull request to our repository to update our version in pom.xml

https://github.com/apache/opennlp-site/pull/20

Closing ticket. Thanks!!

**Comment by jonbullock** [comment]
Excellent 😄
