### ISSUE TITLE
Fix lifecycle mapping of generate mojo

### ISSUE THREAD

**Issue by jonbullock** [jbake-org/jbake-maven-plugin#5]
See ingenieux/jbake-maven-plugin#17 and ingenieux/jbake-maven-plugin#19

**Comment by oliverlietz** [comment]
@jonbullock,  I had some issues with ingenieux/jbake-maven-plugin and wrote a new plugin from scratch (bake, watch, serve) which I pushed to GitHub finally: https://github.com/bildschirmarbeiter/jbake-maven-plugin

**Comment by jonbullock** [comment]
Could you let me know what the issues were you had? 

Thanks for sharing the link to your plugin too, good to see how others have gone about creating a plugin for JBake.

**Comment by oliverlietz** [comment]
The most prominent (and annoying) issue is the crashing directory watcher. I tried with NIO.2 but that does polling on Mac OS and didn't work as reliable as expected (now using VFS2 too).

**Comment by jonbullock** [comment]
Thanks @oliverlietz I've raised an issue to change the solution used.
